backend:
  name: git-gateway
  branch: main # Cambia a tu rama principal si no es "main"

media_folder: "src/assets/uploads" # Dónde se guardan las imágenes
public_folder: "/assets/uploads"  # URL pública para las imágenes

collections:
  - name: "pages"       # Identificador único
    label: "Pages"      # Nombre visible en el CMS
    folder: "src/pages" # Carpeta donde se guardarán las páginas
    create: true        # Permitir crear nuevas páginas
    slug: "{{slug}}"    # Cómo se nombrarán los archivos
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
