backend:
  name: git-gateway
  branch: main # Cambia esto a la rama principal de tu repositorio

media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true # Activar para pruebas locales

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", editor: "visual" }
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", editor: "visual" }
